services:
  db:
    image: 'mysql:latest'
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '3306:3306'
    networks:
      - springboot-net
  app:
    build: .
    container_name: springboot-app
    ports:
      - '9090:8080'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://db:3306/mydb'
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
    networks:
      - springboot-net
networks:
  springboot-net:
    driver: bridge